### ISSUE TITLE
example.rda

### ISSUE THREAD

**Issue by ereverman** [QidiPeng/eQTLMAPT#1]
Hello, It seems like example.rda is empty. To be fair, I haven't used rda objects very much, so maybe I missed something. Any help would be appreciated, thanks!

**Comment by stormlovetao** [comment]
> Hello, It seems like example.rda is empty. To be fair, I haven't used rda objects very much, so maybe I missed something. Any help would be appreciated, thanks!

 `load(file = "example.rda")` will solve your problem.

**Comment by ereverman** [comment]
Thank you. My problem was that I was downloading .rda first, then trying to load it. 

This worked: 
library(RCurl)
load(url("https://github.com/QidiPeng/eQTLMAPT/blob/master/data/example.rda?raw=true"))
